### ISSUE TITLE
Found broken `/graphql/eslint/docs/parser-options` link. Please fix!

### ISSUE THREAD

**Issue by totorean** [the-guild-org/website#1034] opened 2023-01-17 13:39 UTC
Referenced here: https://the-guild.dev/graphql/eslint/docs/getting-started#extended-linting-rules-with-graphql-schema

**Comment by dotansimha** [comment] 2023-01-17 16:57
Thanks @totorean , this seems like a duplicate of https://github.com/the-guild-org/website/issues/1033

**Closed by dotansimha** 2023-01-17 16:57 UTC
